### ISSUE TITLE
Frontend Exception

### ISSUE THREAD

**Issue by devtroll** [straschek-io/typo3-hyphenator#1]
**Error-Message**
`Argument 1 passed to StraschekIo\Hyphenator\Parser\HyphenParser::replace() must be of the type array, null given, called in /var/www/html/public/typo3conf/ext/typo3_hyphenator/Classes/Middleware/HyphenatorMiddleware.php on line 37`

**Solution**
`if($terms) {
            $parsedOutput = $this->parser->replace($terms, $output);
            $response->getBody()->rewind();
            $response->getBody()->write($parsedOutput);
        }`

**Comment by straschek-io** [comment]
Hi @devtroll – thank you for reporting this issue.

It is now resolved with [869b75fccfc](https://github.com/straschek-io/typo3-hyphenator/commit/869b75fccfcf0cfcaf5723ffc4489e8aa4b31075)
