### ISSUE TITLE
Prevent parsing of Title-Tag

### ISSUE THREAD

**Issue by mockmeup** [straschek-io/typo3-hyphenator#2]
The extension inserts soft hyphens not only in the "visible" content, but also in any matched term found in the < head >. 

I don't really see the point in having soft hyphens in the < head > ... and also I don't like it, because - when I hover over the tab in chrome for instance - the browser displays the title with a line break where the soft hyphen is, but without display a "-", which looks strange.

Anyway, maybe (in file HypenParser.php) you could replace replace this

`$content = preg_replace('/(?<=[\>.*\s])' . $term['from'] . '/', $termReplacement, $content);`

with this:

`$content = preg_replace('/(?<=<body>.*)(?<=[\>.*\s])' . $term['from'] . '/', $termReplacement, $content);`

Or am I missing something, and it actually makes sense to have soft hyphens e.g. in the title-Tag?

**Comment by straschek-io** [comment]
@mockmeup Thanks for this issue, i missed it – sorry for that. After playing around with regexes i came to the conclusion that something like following should work: 

`$content = preg_replace('/(?<=[\>.*\s])' . $term['from'] . '(?=[.*\s]\<\/head\>)/', $termReplacement, $content);`

See as well: https://regex101.com/r/b9Dar3/1

**Comment by straschek-io** [comment]
Landed with regex `s` modifier. Fixed then with https://github.com/straschek-io/typo3-hyphenator/commit/8d78e71746787e8abb72d73f9ba3ed231603d8b6

@mockmeup Thanks for reporting, parsing the head was nonsense.

**Comment by mockmeup** [comment]
Cool, it's working! Thank you for fixing this!
