### ISSUE TITLE
Typo3 v12 compatibilty

### ISSUE THREAD

**Issue by mockmeup** [straschek-io/typo3-hyphenator#4]
Hi!

Do you have any plans on making your extension v12 compatible? I just tested it successfully with my site (which runs Typo3 v12), and just had to make minor changes.

Most important was to replace

`defined('TYPO3_MODE') || die('Access denied.');`

with

`defined('TYPO3') || die('Access denied.');`

in file ext_localconf.php because TYPO3_MODE was removed in v12 and resulted in a hard exit of the code.

**Comment by straschek-io** [comment]
@mockmeup Thank you very much. Done with Version 1.40
https://github.com/straschek-io/typo3-hyphenator/tree/1.4.0
